version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: zeus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: zeus
      MYSQL_USER: zeus_user
      MYSQL_PASSWORD: zeus_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  api:
    build: .
    container_name: zeus_api
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: zeus_user
      DB_PASS: zeus_pass
      DB_NAME: zeus
      JWT_SECRET: your_jwt_secret
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
